<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BarTenderPrinter.Domain\BarTenderPrinter.Domain.csproj" />
    <ProjectReference Include="..\BarTenderPrinter.Persistence\BarTenderPrinter.Persistence.csproj" />
    <ProjectReference Include="..\BarTenderPrinter.Devices\BarTenderPrinter.Devices.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.Template.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
